-  참고 문서
-  파이토치로 딥러닝하기: 60분만에 끝장내기
-  https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

# 1. 시작하기 

In [5]:
from __future__ import print_function
import torch

In [7]:
x = torch.tensor([5.5, 3])
print(x)
print(x.size())

tensor([5.5000, 3.0000])
torch.Size([2])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.Size([5, 3])


### 연산(Operations)

In [11]:
y = torch.randn(5, 3)
print(y)
print(x+y)

tensor([[ 0.7863, -0.1889,  0.9182],
        [ 1.0949,  1.3390,  1.1506],
        [-1.3324, -0.1242,  0.1322],
        [-1.2539, -0.9464, -1.4157],
        [-2.7417,  1.4613,  2.4641]])
tensor([[ 1.7863,  0.8111,  1.9182],
        [ 2.0949,  2.3390,  2.1506],
        [-0.3324,  0.8758,  1.1322],
        [-0.2539,  0.0536, -0.4157],
        [-1.7417,  2.4613,  3.4641]], dtype=torch.float64)


### Tensor -> Numpy 변환

In [12]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [13]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


### Numpy 배열 -> Torch Tensor로 변환

In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# 2. 신경망(neural networks)

### 신경망 정의하기

In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [25]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        
        self.fc1 = nn.Linear(16*6*6,  120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [26]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [27]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [28]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0283, -0.0915, -0.1044,  0.0941, -0.0087, -0.0075, -0.0115,  0.0809,
          0.0567, -0.0229]], grad_fn=<AddmmBackward>)
